# Generated by Django 3.0.3 on 2020-03-22 00:55

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tatuador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('alvara', models.CharField(max_length=16, verbose_name='Alvará')),
                ('telefone', models.CharField(max_length=16)),
                ('alvara_digital', stdimage.models.StdImageField(upload_to='tatuadores/alvaras')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endereco.Endereco')),
                ('especializacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Especializacao')),
            ],
            options={
                'verbose_name': 'Tatuador',
                'verbose_name_plural': 'Tatuadores',
            },
        ),
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('data', models.DateField(verbose_name='Data da Certificação')),
                ('titulo', models.CharField(max_length=30, verbose_name='Título')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('codigo', models.CharField(default='QR Code', help_text='Caso o mesmo seja em formato QRcode não altere o valor padrão.', max_length=20, verbose_name='Código de Validação')),
                ('imagem', stdimage.models.StdImageField(upload_to='tatuador/certificacao/', verbose_name='Imagem')),
                ('tatuador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tatuador.Tatuador')),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
                'ordering': ['data_criacao', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('apresentacao', models.TextField(max_length=100, verbose_name='Apresentação')),
                ('conteudo', models.TextField(max_length=2000, verbose_name='Conteúdo')),
                ('tatuador', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tatuador.Tatuador')),
            ],
            options={
                'verbose_name': 'Biografia',
                'verbose_name_plural': 'Biografias',
                'ordering': ['data_criacao', 'tatuador'],
            },
        ),
    ]
