# Generated by Django 3.0.3 on 2020-04-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatuador',
            name='aprovado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Autorização'),
        ),
    ]
