# Generated by Django 3.0.3 on 2020-04-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0002_tatuador_aprovado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='apresentacao',
            field=models.TextField(max_length=260, verbose_name='Apresentação'),
        ),
        migrations.AlterField(
            model_name='certificacao',
            name='descricao',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='certificacao',
            name='titulo',
            field=models.CharField(max_length=60, verbose_name='Título'),
        ),
        migrations.AlterUniqueTogether(
            name='certificacao',
            unique_together={('tatuador', 'titulo')},
        ),
    ]
