# Generated by Django 3.0.3 on 2020-04-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0003_auto_20200407_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tatuador',
            name='especializacao',
        ),
        migrations.AlterField(
            model_name='tatuador',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='tatuador',
            name='telefone',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
