# Generated by Django 3.0.3 on 2020-04-17 20:53

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0004_auto_20200413_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='conteudo',
            field=models.TextField(max_length=10000, verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='certificacao',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='tatuador/certificacao/', verbose_name='Imagem'),
        ),
    ]
