# Generated by Django 3.0.3 on 2020-05-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0006_auto_20200424_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tatuador',
            name='aprovado',
        ),
    ]
