# Generated by Django 3.0.3 on 2020-06-01 13:55

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0007_remove_tatuador_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatuador',
            name='atuando',
            field=models.BooleanField(default=True, verbose_name='Atuando'),
        ),
        migrations.AlterField(
            model_name='tatuador',
            name='alvara_digital',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='tatuadores/alvaras'),
        ),
    ]
