# Generated by Django 3.0.3 on 2020-06-12 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_auto_20200611_2207'),
        ('tatuador', '0008_auto_20200601_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tatuador',
            name='alvara',
        ),
        migrations.RemoveField(
            model_name='tatuador',
            name='alvara_digital',
        ),
        migrations.RemoveField(
            model_name='tatuador',
            name='atuando',
        ),
        migrations.RemoveField(
            model_name='tatuador',
            name='cnpj',
        ),
        migrations.AddField(
            model_name='tatuador',
            name='agenda',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='agenda.Agenda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tatuador',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='tatuador',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='tatuador',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='tatuador',
            name='site_pessoal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Pessoal'),
        ),
        migrations.AddField(
            model_name='tatuador',
            name='wathsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Wathsapp'),
        ),
        migrations.AlterField(
            model_name='certificacao',
            name='tatuador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tatuador.Tatuador'),
        ),
        migrations.AlterField(
            model_name='tatuador',
            name='bio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='tatuador.Bio'),
        ),
        migrations.AlterField(
            model_name='tatuador',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
