# Generated by Django 3.0.3 on 2020-06-12 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_auto_20200611_2207'),
        ('tatuador', '0009_auto_20200611_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatuador',
            name='agenda',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='agenda.Agenda'),
        ),
    ]
