# Generated by Django 3.0.7 on 2020-06-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0010_auto_20200611_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatuador',
            name='cpf_ou_cnpj',
            field=models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], default='cpf', max_length=4, verbose_name='CPF ou CNPJ'),
        ),
    ]
