# Generated by Django 3.0.7 on 2020-07-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0011_tatuador_cpf_ou_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tatuador',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='tatuador',
            name='cpf_ou_cnpj',
        ),
        migrations.AddField(
            model_name='tatuador',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='tatuador',
            name='bio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tatuador.Bio'),
        ),
    ]
