# Generated by Django 3.0.7 on 2020-07-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0012_auto_20200702_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatuador',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
