# Generated by Django 3.0.3 on 2020-09-01 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0013_auto_20200702_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatuador',
            name='bio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tatuador.Bio'),
        ),
    ]
