# Generated by Django 3.0.3 on 2020-04-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.TextField(blank=True, help_text='Informações adicionais sobre o endereço.', max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=4, verbose_name='N°'),
        ),
        migrations.AlterUniqueTogether(
            name='endereco',
            unique_together={('rua', 'numero', 'bairro', 'cidade')},
        ),
    ]
