# Generated by Django 3.0.3 on 2020-05-29 23:39

from django.db import migrations
import endereco.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_auto_20200402_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=endereco.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
