# Generated by Django 3.0.3 on 2020-06-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0003_endereco_imagem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endereco',
            unique_together=set(),
        ),
    ]
