# Generated by Django 3.0.3 on 2020-04-07 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0003_auto_20200407_1413'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['data_criacao']},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tatuador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tatuador.Tatuador'),
        ),
        migrations.AlterField(
            model_name='configuracaoagenda',
            name='dia',
            field=models.CharField(choices=[('', ''), ('segunda', 'Segunda'), ('terca', 'Terça'), ('quarta', 'Quarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('feriado_nacional', 'Feriados Nacionais'), ('feriado_religioso', 'Feriados Religiosos')], default='', max_length=17, verbose_name='Dia'),
        ),
    ]
