# Generated by Django 3.0.3 on 2020-05-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20200529_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conclusaotatuador',
            name='horario',
        ),
        migrations.DeleteModel(
            name='ConclusaoCliente',
        ),
        migrations.DeleteModel(
            name='ConclusaoTatuador',
        ),
    ]
