# Generated by Django 3.0.3 on 2020-06-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20200529_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioagendado',
            name='concluid',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
    ]
