# Generated by Django 3.0.3 on 2020-06-12 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_horarioagendado_concluid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='tatuador',
        ),
        migrations.DeleteModel(
            name='HorarioAgendado',
        ),
    ]
