# Generated by Django 3.0.3 on 2020-03-22 00:55

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicacao', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDenuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('aviso', models.CharField(default='Nenhuma', help_text='descreva as implicações ao se usar esse tipo de denúncia', max_length=60, verbose_name='Implicações')),
            ],
            options={
                'verbose_name': 'Tipo de Denúncia',
                'verbose_name_plural': 'Tipos de Denúncia',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='DenunciaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to='usuario/denuncia/')),
                ('denunciado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncia_usuario_denunciado', to='usuario.Usuario')),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Usuario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.TipoDenuncia')),
            ],
            options={
                'verbose_name': 'Denúncias contra Usuários',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='DenunciaPublicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Usuario')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicacao.Publicacao')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncia.TipoDenuncia')),
            ],
            options={
                'verbose_name': 'Denúncias contra Publicações',
                'ordering': ['data_criacao'],
            },
        ),
    ]
