# Generated by Django 3.0.3 on 2020-05-29 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20200417_1753'),
        ('denuncia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denunciapublicacao',
            options={'ordering': ['data_criacao'], 'verbose_name': 'Denúncia contra Publicações'},
        ),
        migrations.AlterModelOptions(
            name='denunciausuario',
            options={'ordering': ['data_criacao'], 'verbose_name': 'Denúncia contra Usuários'},
        ),
        migrations.AlterField(
            model_name='denunciausuario',
            name='denunciado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncia_usuario_denunciado', to='usuario.Usuario'),
        ),
        migrations.AlterField(
            model_name='tipodenuncia',
            name='aviso',
            field=models.CharField(default='Nenhuma', help_text='Descreva as implicações ao se usar esse tipo de denúncia', max_length=60, verbose_name='Implicações'),
        ),
    ]
