# Generated by Django 3.0.7 on 2020-06-22 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('denuncia', '0002_auto_20200529_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denunciapublicacao',
            name='denunciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='denunciapublicacao',
            name='descricao',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='denunciausuario',
            name='denunciado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncia_usuario_denunciado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='denunciausuario',
            name='denunciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='denunciausuario',
            name='descricao',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Descrição'),
        ),
    ]
