# Generated by Django 3.0.7 on 2020-06-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0003_auto_20200622_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denunciapublicacao',
            options={'ordering': ['data_criacao'], 'verbose_name': 'Denúncia contra Publicação', 'verbose_name_plural': 'Denúncia contra Publicações'},
        ),
    ]
