# Generated by Django 3.0.3 on 2020-04-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='especializacao',
        ),
        migrations.RemoveField(
            model_name='pedidoorcamento',
            name='cliente',
        ),
    ]
