# Generated by Django 3.0.3 on 2020-04-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20200413_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoorcamento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
    ]
