# Generated by Django 3.0.3 on 2020-05-29 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_pedidoorcamento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoorcamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
        migrations.AlterField(
            model_name='pedidoorcamento',
            name='tamanho',
            field=models.CharField(help_text='Altura: 40cm x Largura: 20cm ', max_length=40, verbose_name='Tamanho'),
        ),
    ]
