# Generated by Django 3.0.3 on 2020-06-12 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_auto_20200611_2207'),
        ('usuario', '0006_auto_20200611_2207'),
        ('cliente', '0004_auto_20200529_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoorcamento',
            name='cliente',
        ),
        migrations.AddField(
            model_name='pedidoorcamento',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
