# Generated by Django 3.0.3 on 2020-06-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20200611_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoOrcamento',
        ),
    ]
