# Generated by Django 3.0.3 on 2020-03-22 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('tipo', models.CharField(help_text='Se refere ao tipo da notificção', max_length=20, verbose_name='Tipo')),
                ('cor', models.CharField(choices=[('Muted', 'muted'), ('Primary', 'primary'), ('Success', 'success'), ('Info', 'info'), ('Warning', 'warning'), ('Danger', 'danger'), ('Secondary', 'secondary'), ('Dark', 'dark'), ('Body', 'body'), ('Light', 'light'), ('White', 'white')], help_text='Cor usada na apresentação da Notificação', max_length=9, verbose_name='Cor')),
                ('descricao', models.TextField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Notificação',
                'verbose_name_plural': 'Tipos de Notificação',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(max_length=20, verbose_name='Título')),
                ('conteudo', models.TextField(max_length=200, verbose_name='Conteúdo')),
                ('destinatario', models.ManyToManyField(related_name='destinatarios', to='usuario.Usuario')),
                ('emissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacao.TipoNotificacao')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
    ]
