# Generated by Django 3.0.3 on 2020-04-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0002_auto_20200330_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiponotificacao',
            name='tipo',
            field=models.CharField(help_text='Se refere ao tipo da notificação', max_length=20, verbose_name='Tipo'),
        ),
    ]
