# Generated by Django 3.0.3 on 2020-05-29 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificacao', '0005_auto_20200402_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebido', models.BooleanField(default=False, verbose_name='Recebido')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('notificao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacao.Notificacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),       
    ]
