# Generated by Django 3.0.3 on 2020-05-29 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificacao', '0006_auto_20200529_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='destinatario',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='destinatarios',
            field=models.ManyToManyField(through='notificacao.NotificacaoUsuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
