# Generated by Django 3.0.3 on 2020-05-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0007_auto_20200529_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='destinatarios',
        ),
    ]
