# Generated by Django 3.0.3 on 2020-05-29 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificacao', '0008_remove_notificacao_destinatarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='emissor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissor', to=settings.AUTH_USER_MODEL),
        ),
    ]
