# Generated by Django 3.0.3 on 2020-05-29 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificacao', '0009_auto_20200529_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='destinatarios',
            field=models.ManyToManyField(through='notificacao.NotificacaoUsuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
