# Generated by Django 3.0.3 on 2020-03-22 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('desenhista', models.BooleanField(default=False, verbose_name='Desenhista')),
                ('administrador', models.BooleanField(default=False, verbose_name='Administrador')),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to='usuario/foto_perfil/', verbose_name='Imagem')),
                ('usuario', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Especializacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('celular', models.CharField(max_length=16, unique=True, verbose_name='N° Celular')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
            options={
                'ordering': ['data_criacao', 'nome'],
                'abstract': False,
            },
        ),
    ]
