# Generated by Django 3.0.3 on 2020-04-03 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200324_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especializacao',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
