# Generated by Django 3.0.3 on 2020-04-13 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0004_auto_20200413_1957'),
        ('cliente', '0002_auto_20200413_1957'),
        ('usuario', '0003_auto_20200403_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especializacao',
            options={'ordering': ['data_criacao', 'nome'], 'verbose_name': 'Especialização', 'verbose_name_plural': 'Especializações'},
        ),
        migrations.RemoveField(
            model_name='especializacao',
            name='usuario',
        ),
        migrations.AddField(
            model_name='especializacao',
            name='cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
        migrations.AddField(
            model_name='especializacao',
            name='tatuador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tatuador.Tatuador'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='especializacao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Especializacao'),
        ),
    ]
