# Generated by Django 3.0.3 on 2020-06-12 01:07

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0009_auto_20200611_2207'),
        ('usuario', '0005_auto_20200417_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoOrcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(max_length=20, verbose_name='Titulo')),
                ('texto_receptivo', models.CharField(max_length=100, verbose_name='Recepção')),
                ('parte_corpo', models.CharField(max_length=20, verbose_name='Parte do corpo')),
                ('img_1', stdimage.models.StdImageField(blank=True, null=True, upload_to='cliente/pedido_orcamento/')),
                ('img_2', stdimage.models.StdImageField(blank=True, null=True, upload_to='cliente/pedido_orcamento/')),
                ('img_3', stdimage.models.StdImageField(blank=True, null=True, upload_to='cliente/pedido_orcamento/')),
                ('tamanho', models.CharField(help_text='Altura: 40cm x Largura: 20cm ', max_length=40, verbose_name='Tamanho')),
                ('texto_complementar', models.TextField(max_length=300, verbose_name='Especificações e Descrição')),
                ('preco_esperado', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor esperado')),
                ('tatuadores', models.ManyToManyField(limit_choices_to=6, related_name='tatuadores', to='tatuador.Tatuador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='especializacao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='', max_length=300, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='tatuador',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='tatuador.Tatuador'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Especializacao',
        ),
        migrations.AddField(
            model_name='pedidoorcamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_solicitante', to='usuario.Usuario'),
        ),
    ]
