# Generated by Django 3.0.7 on 2020-06-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0010_auto_20200611_2208'),
        ('usuario', '0006_auto_20200611_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tatuador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tatuador.Tatuador'),
        ),
    ]
