# Generated by Django 3.0.7 on 2020-07-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0011_tatuador_cpf_ou_cnpj'),
        ('usuario', '0007_auto_20200623_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tatuador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tatuador.Tatuador'),
        ),
    ]
