# Generated by Django 3.0.7 on 2020-07-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20200702_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoorcamento',
            name='preco_esperado',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor Esperado'),
        ),
        migrations.AlterField(
            model_name='pedidoorcamento',
            name='texto_receptivo',
            field=models.CharField(max_length=1000, verbose_name='Recepção'),
        ),
        migrations.AlterField(
            model_name='pedidoorcamento',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Titulo'),
        ),
    ]
