# Generated by Django 3.0.7 on 2020-07-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatuador', '0013_auto_20200702_1047'),
        ('usuario', '0009_auto_20200720_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoorcamento',
            name='tatuadores',
            field=models.ManyToManyField(related_name='tatuadores', to='tatuador.Tatuador'),
        ),
        migrations.AlterField(
            model_name='pedidoorcamento',
            name='texto_complementar',
            field=models.TextField(max_length=2500, verbose_name='Especificações e Descrição'),
        ),
    ]
