# Generated by Django 3.0.3 on 2020-03-30 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicacao', '0003_auto_20200329_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='titulo',
            field=models.CharField(max_length=60, verbose_name='Título'),
        ),
        migrations.AlterUniqueTogether(
            name='aprovacao',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='aprovacao',
            name='publicacao',
        ),
    ]
