# Generated by Django 3.0.3 on 2020-03-30 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200324_0933'),
        ('publicacao', '0005_auto_20200329_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='aprovacoes',
        ),
        migrations.AddField(
            model_name='aprovacao',
            name='publicacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='publicacao.Publicacao'),
        ),
        migrations.AlterField(
            model_name='aprovacao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuario.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='aprovacao',
            unique_together={('publicacao', 'usuario')},
        ),
    ]
