# Generated by Django 3.0.3 on 2020-03-31 00:11

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0006_auto_20200329_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='midia',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='usuario/publicacoes/'),
        ),
    ]
