# Generated by Django 3.0.7 on 2020-06-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0007_auto_20200330_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='conteudo',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
